### ISSUE TITLE
pdftoppm not Found

### ISSUE THREAD

**Issue by ddmarshall** [UB-Mannheim/zotero-ocr#16]
Using v.0.3.0 on linux with Zotero v 5.0.89. I'm using the standard Ubuntu 20.04 installation of tesseract and pdftoppm (both located in /usr/bin).

To reproduce:
- Install latest verion
- Right click on a PDF to OCR

This results in the following error message:
Cannot find /usr/local/Zotero_linux-x86_64/pdftoppm

Work-around is to create symbolic link to the system pdftoppm in /usr/local/Zotero_linux-x86_64.

**Comment by githubnavigator** [comment]
This same issue is on all the platforms.

Can the plug-in just check to see if pdftoppm is already in the system path, and then use that? I have it installed on both my Mac and PC and can call it from anywhere in my system at the command line because it's in the path. But in Zotero I need to drag and drop the file. On Windows I also have to drag and drop all the poppler DLLs into the Zotero folder as well as the pdftoppm.exe file. Or can you just let us put the path to the poppler files in there like you allow us to do with the tesseract executable?

**Comment by llity** [comment]
I have the same issue

**Comment by stweil** [comment]
The README describes the prerequisites: "pdftoppm from poppler library is downloaded and copied to the other scripts in the Zotero directory". Creating a symbolic link is fine, too.

So this is a documented feature. Not using `PATH` makes sure that a well defined `pdftoppm` is used.

The poppler path could be added to the settings. Do you want to send a pull request which implements the suggested change?

**Comment by githubnavigator** [comment]
The problem is moving DLLs and exe files around in system directories like this or creating symbolic links is above the technical level of some of the people I am trying to support (actually, _all_ of the people I'm trying to help, unfortunately). Telling them to install Poppler and Tesseract and then add the location to those programs is more straightforward. Calling Poppler from its location also allows the plug-in to continue using the most recent/secure version whenever Poppler gets updated.

**Comment by CRTified** [comment]
Using the system path or a configurable setting also solves the dependency problem for declarative systems like NixOS, where neither `poppler_utils` nor `tesseract` are copied into the zotero path (and they're not even dependencies of zotero itself). While setting the path for `tesseract` is fine, not being able to set the path for `pdftoppm` is a blocker for me.

**Comment by zuphilip** [comment]
There is now a new option to configure the path to pdftoppm. Please try it out in the new version 0.4.0. For any new problems you can open another issue. / CC @ddmarshall @llity @githubnavigator @CRTified

**Comment by dummifiedme** [comment]
Can there be a detailed explanation on how to installed pdftoppm?
I am on Manjaro Linux, and have both the poppler and utils installed on the system. 
Where do I have to get the files from?

**Comment by CRTified** [comment]
@dummifiedme 
`pdftoppm` is part of the utils package.
After installing, it is likely that `pdftoppm` can be found in `/usr/bin/`.

If you can run `pdftoppm` in a shell, it is in one of the paths in the environment variable `$PATH`. In this case, you can identify the full path by running `whereis pdftoppm`.

**Comment by dummifiedme** [comment]
Thanks!
I found the package at `/usr/bin/`

Now, if I run the OCR command, will it show any visual confirmation that the process has started or when it is finished?
Currently, I don't see any error popup but nothing particularly different. Plus, opening the PDF shows file invalid error.
