### ISSUE TITLE
Resulting PDF is invalid (on M1 Macbook)

### ISSUE THREAD

**Issue by AndrewRRM** [UB-Mannheim/zotero-ocr#27]
Not sure if this is the right place for a help request so feel free to move or delete this post. I've already posted over at the Zotero forum.

I cannot get this to work.

I've installed tesseract and poppler with Homebrew, installed the zotero plugin and set the path in the Zotero plugin to:

(/opt/homebrew/Cellar/tesseract/4.1.1
/opt/homebrew/Cellar/poppler/21.03.0_1/bin

I can confirm that this where those files do live.

I've also copied the pdftoppm into /Applications/Zotero.app/Contents/MacOS/pdftoppm according a recommendation on the Zotero forum, although I have tried to run the ocr with and without this step.

When I run the plugin, an ocr file appears but when I try to open it I get the following error:

Format Error: Not a PDF or corrupted.

PDF.js v2.8.146 (build: 7dd64325d)
Message: Invalid PDF structure.

Help? ...

**Comment by zuphilip** [comment]
Can you save the extracted text in a text note?

It sounds like the steps are running through and then only the resulting PDF is invalid. Does this happen with every PDF you try? If yes, can you share the resulting PDF and the one you started with here as an example?

**Comment by AndrewRRM** [comment]
Sorry for the slow reply. Actually, I have no error anymore. In fact, nothing happens when I try to ocr now. Doesn't matter what pdf I attempt.

**Comment by otheivan** [comment]
Hi,

I have the same or a similar problem with Zotero on Windows 10.

When I run OCR a command prompt for pdftoppm pops up and just sits there without doing anything, even left it for about 30 minutes but nothing (I should say, it does something since the cpu seems to react, but I don't know what). When I close down pdftoppm a command prompt for tesseract pops up and seems to do its thing however, the pdf that it saves is corrupt. Tried a few pdf-readers just to be sure.

Also worth noting, if I turn on "Save output as a note" it does seem to work but not every time.

Running Zotero 5.0.96.2 with the latest Zotero OCR, tesseract and poppler for windows 21.03.0.

Let me know if you need anything else.

**Comment by stweil** [comment]
The "path" settings require the full path of the executables, not only the directory part. These settings work for me on MacOS with M1:

![Bildschirmfoto 2021-06-06 um 16 36 59](https://user-images.githubusercontent.com/6734573/120928616-9a17e600-c6e5-11eb-8398-8fa1cc997015.png)

**Comment by zuphilip** [comment]
I am closing this, since the initial question by @AndrewRRM seems to be answered by @stweil.

@otheivan If you have still any issues, then please open another issue about it. I think it is easier to seperate the different operating systems on these issues.
