### ISSUE TITLE
bugs with newest version & questions on developing

### ISSUE THREAD

**Issue by Alex4210987** [UB-Mannheim/zotero-ocr#71]
hi developers! thanks for your excellent work!
i have 2 questions :
- i guess there is some bugs about the newest 0.7.1 ver., actually when i use it with windows, it did nothing at alll; however when i use 0.7.0 it works.
- i'd like to redeveloped it with an ocr api. would you kindly tell me how may i where i should modify it ?

**Comment by aborel** [comment]
0.7.1 had an important bug using Zotero7, 0.7.2 is intended to fix that.

If you want to redesign the plugin around a different OCR engine, especially using an API instead of calling external programs as zotero-ocr is currently, I think you will need to modify almost everything. Most of the code deals with calling the external tools `pdftoppm`and `tesseract` in the proper sequence and using the proper parameter, and the preferences are quite specific to these tools.

**Comment by Alex4210987** [comment]
yesss, you are right about changing everything. i guess it's a lot of work.

however, the bug i described happens on Zotero6.  sorry that i'm that specific enough before.

**Comment by aborel** [comment]
Can you post screenshots of your Zotero-OCR preferences and the folder for the Zotero item?

**Comment by stweil** [comment]
Are there remaining bugs with the latest release 0.8.1? Or can this issue be closed?

**Comment by aborel** [comment]
It feels OK to close.
